name: 'Google Chat Pipeline notifications'
description: 'Google chat notifications'
inputs:
  webHookURL:
    description: 'Google Chat Webhook URL'
    required: true
  env:
    description: 'CloudIA ENV'
    required: true
  version:
    description: 'Release version'
    required: true
  status:
    description: 'Workflow status'
    required: true
  threadId:
    description: 'Thread Id'
runs:
  using: 'node16'
  main: 'dist/index.js'
